version: '3.8'

services:
  flask-app:
    image: mirosh137/flaskapp:1.0  # Use the correct image from Docker Hub
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_HOST: db  # MySQL service hostname
      DATABASE_USER: root
      DATABASE_PASSWORD: 13478DanilaM_
      DATABASE_NAME: gifs_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 13478DanilaM_
      MYSQL_DATABASE: gifs_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./gifdb.sql:/docker-entrypoint-initdb.d/gifdb.sql

volumes:
  mysql_data:
