replicaCount: 2

image:
  repository: mirosh137/flaskapp
  tag: "1.0"

mysql:
  replicaCount: 1
  image: "mysql:8.0"
  secretName: "mysql-secret"
  password: "13478DanilaM_"  # ✅ Now defined for Helm to use
  serviceName: "mysql-service"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: false

