apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  gifdb.sql: |
    CREATE DATABASE IF NOT EXISTS gifs_db;
    USE gifs_db;
    CREATE TABLE IF NOT EXISTS gifs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        url VARCHAR(255) NOT NULL
    );
    INSERT INTO gifs (url) VALUES
    ('https://media.giphy.com/media/3o7TKU8RvQuomFfUUU/giphy.gif'),
    ('https://media.giphy.com/media/26AHONQ79FdWZhAI0/giphy.gif'),
    ('https://media3.giphy.com/media/CjmvTCZf2U3p09Cn0h/giphy.gif'),
    ('https://media.giphy.com/media/26gssIytJvy1b1THO/giphy.gif'),
    ('https://media.giphy.com/media/pT1dcZcJfhQZy/giphy.gif'),
    ('https://media.giphy.com/media/yoJC2GnSClbPOkV0eA/giphy.gif'),
    ('https://media.giphy.com/media/Z5xk7fGO5FjjTElnpT/giphy.gif'),
    ('https://media.giphy.com/media/l0Exk8EUzSLsrErEQ/giphy.gif');
