name: Terraform Deployment

on:
  workflow_run:
    workflows: ["Flask App CI/CD Pipeline"]
    types:
      - completed
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  PROJECT_ID: my-new-gke-project-452612
  GKE_CLUSTER: my-gke-cluster
  GKE_REGION: us-central1-a

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform-deployment
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan
        working-directory: terraform-deployment
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan
        working-directory: terraform-deployment
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}

  deploy:
    name: Deploy to GKE with Helm
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Install GKE Auth Plugin for kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Get GKE Cluster Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION

      - name: Install Specific Helm Version
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version

      - name: Deploy to GKE Using Helm
        run: |
          helm upgrade --install flaskapp-release ./flaskapp-chart --namespace default \
            --set image.repository=${{ secrets.GCR_HOSTNAME }}/my-new-gke-project-452612/flaskapp-repo/flaskapp \
            --set image.tag=latest

        
