name: Terraform Deployment

on:
  workflow_run:
    workflows: ["Flask App CI/CD Pipeline"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
     
      - name: List Repository Files
        run: ls -R

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform -chdir=terraform-deployment init

      - name: Terraform Plan
        run: terraform -chdir=terraform-deployment plan -input=false -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Apply
        run: terraform -chdir=terraform-deployment apply -auto-approve -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
